project:
  type: website

website:
  title: "Street-Fighting Analytics"
  favicon: favicon.png
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/brickbrycebrick
      - icon: linkedin
        href: https://www.linkedin.com/in/bryceklein3/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
