project:
  type: website
  resources:
    - CNAME

website:
  title: "Street-Fighting Analytics"
  favicon: favicon.png
  search:
    keyboard-shortcut: ["f", "/"]
    show-item-context: true
    copy-button: true
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/brickbrycebrick
      - icon: linkedin
        href: https://www.linkedin.com/in/bryceklein3/
format:
  html:
    theme: default
    css: styles.css
    highlight-style: github-dark
    toc: true
    toc-title: Contents
    toc-location: right
    toc-depth: 2
    callout-appearance: simple
    link-external-newwindow: true
